name: 📝 New Issue
description: バグ報告、機能要望、その他タスクを作成するためのフォーム
title: ''
labels: ''
assignees: []

body:
  - type: dropdown
    id: type
    attributes:
      label: 種類 (Type)
      description: いずれか1つ選択してください
      options:
        - value: fix
          label: 💥 fix: バグ修正
        - value: feature
          label: ✨ feature: 新機能追加
        - value: docs
          label: 📝 docs: ドキュメント変更
        - value: style
          label: 🎨 style: スタイル変更（機能に影響なし）
        - value: refactor
          label: ♻️ refactor: リファクタリング（機能変更なし）
        - value: test
          label: ✅ test: テスト追加・修正
        - value: chore
          label: 🔧 chore: 補助ツール／ビルド変更
        - value: ci
          label: 🔀 ci: CI/CD 設定変更

  - type: input
    id: summary
    attributes:
      label: 概要
      description: 何をしたいのかを簡潔に記載してください
      placeholder: "例: ログイン画面でエラーが発生する"
      required: true

  - type: textarea
    id: description
    attributes:
      label: 詳細
      description: 変更内容や要件、背景などを詳しく記載します
      placeholder: |
        - 追加した機能の概要  
        - 変更した理由
      required: false

  - type: textarea
    id: steps
    attributes:
      label: 再現手順（バグの場合）
      description: 番号付きで記載してください
      placeholder: |
        1. サイトにアクセス  
        2. ログインをクリック  
        3. エラーが表示される  
      required: false

  - type: textarea
    id: expected
    attributes:
      label: 期待される動作
      required: false

  - type: textarea
    id: actual
    attributes:
      label: 実際の動作（バグの場合）
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 追加情報（任意）
      description: スクリーンショット、ログ、環境情報など

  - type: input
    id: related
    attributes:
      label: 関連 Issue / PR
      description: Closes #123 のように番号を記載
      placeholder: "Closes #123"
      required: false