version: '3.8'

services:
  audio-analyzer:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
    volumes:
      - .:/app
      - /app/.venv
    depends_on:
      - redis
    networks:
      - sonory-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sonory-network

volumes:
  redis_data:

networks:
  sonory-network:
    driver: bridge 