name: Assign Author

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  assign:
    name: Assign author to Issue or PR
    runs-on: ubuntu-latest
    steps:
      - name: Assign author
        uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 